### ISSUE TITLE
 Module update to the latest version of discord.js

### ISSUE THREAD

**Issue by DerexM** [slash-labs/fast-webhook#1]
Recently, discord js team has released a new version of the discord.js module. Fase-webhook is not working properly because discord.js has changed webhook upload functionality.

error: 
![image](https://user-images.githubusercontent.com/58607083/128772905-c9b2a688-9ce6-4721-9d7b-d932d40a0514.png)
![image](https://user-images.githubusercontent.com/58607083/128772945-4fec39d1-073a-4c1d-bede-6fd28fc5fe3a.png)

I will be grateful if the problem is fixed. I am using this module.

Change:
![image](https://user-images.githubusercontent.com/58607083/128824213-979d80a7-5183-4995-a62e-98a3eff01797.png)
to:
![image](https://user-images.githubusercontent.com/58607083/128824290-42854e1a-c9eb-4b0f-8f03-b3af63046fcc.png)

**Comment by DomeQdev** [comment]
fast webhook is no longer supported, sorry.
